#!/bin/bash

CANDLEHOME=/opt/IBM/ITM
SILENT_CONFIG="/cq_config.txt"

# Add runtime configuration properties to silent config file
for e in ADMINISTRATORID ADMINISTRATORPW BK1NETWORKPROTOCOL BK2NETWORKPROTOCOL CMSCONNECT DB2ATTR DB2CREATEID DB2ID DB2INSTANCE DB2NAME DB2PW DBATTR_1 DBATTR_2 DBID_1 DBID_2 DBNAME_1 DBNAME_2 DBPW_1 DBPW_2 FIREWALL HOSTNAME IPPIPEPORTNUMBER IPSPIPEPORTNUMBER KD8_HUBNAME_OVERRIDE KD8_ITM_REST_SERVICE_ENABLE KDC_PARTITIONFILE KDC_PARTITIONNAME KDQ_GS_ENABLE_POLICY_AUTH KDQ_GS_POLICY_SERVER_ADDRESS KDQ_GS_POLICY_SERVER_PORT KDQ_GS_POLICY_SERVER_PWD KDQ_GS_POLICY_SERVER_USERID KDQ_GS_POLICY_STORE_EXP_DAYS KDQ_GS_POLICY_STORE_EXP_HOURS KDQ_GS_POLLING_INTERVAL KDQ_GS_WEB_PROTOCOL KFW_JDBC_DRIVER KFW_LDAP_BIND_DN KFW_LDAP_BIND_PWD KFW_LDAP_DN_BASE_ENTRY KFW_LDAP_ENABLED KFW_LDAP_HOST_NAME KFW_LDAP_PORT KFW_LDAP_ROOT KFW_LDAP_SERVER_TYPE KFW_LDAP_SSO_DOMAIN KFW_LDAP_SSO_ENABLED KFW_LDAP_SSO_REALM KFW_STARTJVM LOGMODE LUNAME NETNAME NETWORKPROTOCOL PORTNUMBER PRIMARYIP TEPSDATABASETYPE WAREHOUSEDB WAREHOUSEID WAREHOUSEPW WHATTR WHATYPE WHCLASS WHURL;
do
        [[ -n "\$${e}" ]] && echo "${e}=\$${e}" >>${SILENT_CONFIG}
done

# Run silent config file
setarch $(uname -m) --uname-2.6 ${CANDLEHOME}/bin/itmcmd config -A -p ${SILENT_CONFIG} cq
setarch $(uname -m) --uname-2.6 ${CANDLEHOME}/bin/itmcmd agent start cq
tail -f ${CANDLEHOME}/logs/kfwservices.msg
setarch $(uname -m) --uname-2.6 ${CANDLEHOME}/bin/itmcmd agent stop cq
