#!/bin/bash

trap 'echo "Shutting down"; exit 0' SIGTERM SIGINT SIGHUP

for e in MS_CMSTYPE MS_FIREWALL MS_NETWORKPROTOCOL MS_BK1NETWORKPROTOCOL MS_BK2NETWORKPROTOCOL MS_BK3NETWORKPROTOCOL MS_BK4NETWORKPROTOCOL MS_BK5NETWORKPROTOCOL MS_HOSTNAME MS_IP6HOSTNAME MS_IPPIPEPORTNUMBER MS_IP6PIPEPORTNUMBER MS_KDC_PARTITIONNAME MS_KDC_PARTITIONFILE MS_IPSPIPEPORTNUMBER MS_IP6SPIPEPORTNUMBER MS_PORTNUMBER MS_IP6PORTNUMBER MS_NETNAME MS_LUNAME MS_LOGMODE MS_AUDIT MS_FTO MS_OKFTO MS_HSNETWORKPROTOCOL MS_BK1HSNETWORKPROTOCOL MS_BK2HSNETWORKPROTOCOL MS_BK3HSNETWORKPROTOCOL MS_BK4HSNETWORKPROTOCOL MS_BK5HSNETWORKPROTOCOL MS_MIRROR MS_IP6MIRROR MS_HSIPPIPEPORTNUMBER MS_HSPORTNUMBER MS_HSNETNAME MS_HSLUNAME MS_HSLOGMODE MS_PRIMARYIP MS_SECURITY MS_TEC_EIF MS_TEC_HOST MS_TEC_PORT MS_WORKFLOW MS_KMS_SECURITY_COMPATIBILITY_MODE;
do
        [[ -n "\$${e##*_}" ]] && echo "${e##*_}=\$${e##*_}"
done


read DUMMY
